# frozen_string_literal: true

require 'nokogiri'
require 'open-uri'
require 'rubygems'
require 'atom'
require 'minitest/autorun'
require 'active_support/core_ext/hash/conversions'
require_relative '../lib/reader/file_reader'
require_relative '../lib/reader/url_reader'
require_relative '../lib/rss/data_reader_for_rss'
require_relative '../lib/rss/atom_builder_for_rss'
require_relative '../lib/rss/rss_builder_for_rss'
require_relative '../lib/atom/data_reader_for_atom'
require_relative '../lib/atom/atom_builder_for_atom'
require_relative '../lib/atom/rss_builder_for_atom'
require_relative '../lib/option/reverse'
require_relative '../lib/option/sort_for_atom'
require_relative '../lib/option/sort_for_rss'
