# frozen_string_literal: true

require 'nokogiri'
require 'open-uri'
require 'rubygems'
require 'atom'
require 'minitest/autorun'
require 'active_support/core_ext/hash/conversions'
require_relative '/home/xmas/code/convert-feed/reader/file_reader.rb'
require_relative '../reader/url_reader'
require_relative '../rss/data_reader_for_rss'
require_relative '../rss/atom_builder_for_rss'
require_relative '../rss/rss_builder_for_rss'
require_relative '../atom/data_reader_for_atom/'
require_relative '../atom/atom_builder_for_atom'
require_relative '../atom/rss_builder_for_atom'
require_relative '/home/xmas/code/convert-feed/option/reverse'
require_relative '/home/xmas/code/convert-feed/option/sort_for_atom'
require_relative '/home/xmas/code/convert-feed/option/sort_for_rss'
