# frozen_string_literal: true

require 'optparse'
require 'rss'
require_relative 'rss/data_reader_for_rss'
require_relative 'reader/file_reader'
require_relative 'reader/url_reader'
require_relative 'rss/atom_builder_for_rss'
require_relative 'rss/rss_builder_for_rss'
require_relative 'atom/data_reader_for_atom'
require_relative 'atom/atom_builder_for_atom'
require_relative 'atom/rss_builder_for_atom'
require_relative 'option/reverse'
require_relative 'option/sort_for_atom'
require_relative 'option/sort_for_rss'
